version: '3.7'

services:
  keila:
    image: pentacent/keila:latest
    container_name: keila
    restart: unless-stopped
    ports:
      - "80:80"  # Expose port 4000 ke port 80 (akses melalui browser)
    environment:
      DB_URL: postgres://keila_user:keila_password@db/keila_db
      SECRET_KEY_BASE: RYQHmEUGGMbskJmy0JLInFlfFOIHuwpJW6pY8n7ZQGRJ3bKCdY1RLK1Nh23E06B7
      URL_HOST: www.keila-komdat-p2-kelompok7.me
      URL_SCHEMA: http  # Gunakan "http" jika tidak menggunakan SSL
      PORT: 80  # Port internal untuk Keila
      MAILER_TYPE: smtp
      MAILER_SMTP_HOST: smtp.gmail.com
      MAILER_SMTP_PORT: 587
      MAILER_SMTP_USER: ahmadsubhan@apps.ipb.ac.id
      MAILER_SMTP_PASSWORD: "umrx nofd iyzc oiar"
      MAILER_SMTP_FROM_EMAIL: ahmadsubhan@apps.ipb.ac.id
      MAILER_ENABLE_SSL: "false"
      MAILER_ENABLE_STARTTLS: "true"
      MAILER_ENABLE_STARTTLS: "true"

    depends_on:
      - db

  db:
    image: postgres:13
    container_name: keila_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: keila_user
      POSTGRES_PASSWORD: keila_password
      POSTGRES_DB: keila_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

