version: '3'

services:
  keila:
    image: pentacent/keila:latest
    container_name: keila
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      DB_URL: postgres://keila_user:keila_password@db/keila_db
      SECRET_KEY_BASE: <your-secret-key-base>
      URL_HOST: <your-domain-or-ip-address>
      URL_SCHEMA: http
      PORT: 80 
      MAILER_TYPE: smtp
      MAILER_SMTP_HOST: <your-smtp-host>
      MAILER_SMTP_PORT: 587
      MAILER_SMTP_USER: <your-smtp-user>
      MAILER_SMTP_PASSWORD: <your-smtp-password>
      MAILER_SMTP_FROM_EMAIL: <your-stmp-email>
      MAILER_ENABLE_SSL: "false"
      MAILER_ENABLE_STARTTLS: "true"
      MAILER_ENABLE_STARTTLS: "true"

    depends_on:
      - db

  db:
    image: postgres:13
    container_name: keila_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: keila_user
      POSTGRES_PASSWORD: keila_password
      POSTGRES_DB: keila_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

